package joojoo.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReviewComment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** comment_code. */
	private Integer commentCode;

	/** owner_id. */
	private String ownerId;

	/** title. */
	private String title;

	/** content. */
	private String content;

	/** reg_date. */
	private Date regDate;

	/** star_point. */
	private Integer starPoint;

	/** 새 테이블. */
	private Stores stores;

	/**
	 * 생성자.
	 */
	public ReviewComment() {
	}

	/**
	 * comment_code을 설정합니다..
	 * 
	 * @param commentCode
	 *            comment_code
	 */
	public void setCommentCode(Integer commentCode) {
		this.commentCode = commentCode;
	}

	/**
	 * comment_code을 가져옵니다..
	 * 
	 * @return comment_code
	 */
	public Integer getCommentCode() {
		return this.commentCode;
	}

	/**
	 * owner_id을 설정합니다..
	 * 
	 * @param ownerId
	 *            owner_id
	 */
	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * owner_id을 가져옵니다..
	 * 
	 * @return owner_id
	 */
	public String getOwnerId() {
		return this.ownerId;
	}

	/**
	 * title을 설정합니다..
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * title을 가져옵니다..
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * content을 설정합니다..
	 * 
	 * @param content
	 *            content
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * content을 가져옵니다..
	 * 
	 * @return content
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * reg_date을 설정합니다..
	 * 
	 * @param regDate
	 *            reg_date
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * reg_date을 가져옵니다..
	 * 
	 * @return reg_date
	 */
	public Date getRegDate() {
		return this.regDate;
	}

	/**
	 * star_point을 설정합니다..
	 * 
	 * @param starPoint
	 *            star_point
	 */
	public void setStarPoint(Integer starPoint) {
		this.starPoint = starPoint;
	}

	/**
	 * star_point을 가져옵니다..
	 * 
	 * @return star_point
	 */
	public Integer getStarPoint() {
		return this.starPoint;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param stores
	 *            새 테이블
	 */
	public void setStores(Stores stores) {
		this.stores = stores;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Stores getStores() {
		return this.stores;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commentCode == null) ? 0 : commentCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReviewComment other = (ReviewComment) obj;
		if (commentCode == null) {
			if (other.commentCode != null) {
				return false;
			}
		} else if (!commentCode.equals(other.commentCode)) {
			return false;
		}
		return true;
	}

}
