package joojoo.entity;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Coupon implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** coupon_code. */
	private String couponCode;

	/** 새 테이블. */
	//private Owners owners;
	private String ownerId;

	/** 새 테이블. */
	//private Users users;
	private String userId;

	/** 새 테이블. */
	//private EventComment eventComment;
	private int commentCode;

	/** 새 테이블. */
	//private CouponStatus couponStatus;
	private String couponStatus;

	/**
	 * 생성자.
	 */
	public Coupon() {
	}

	
	public Coupon(String couponCode, String ownerId, String userId,
			int commentCode, String couponStatus) {
		super();
		this.couponCode = couponCode;
		this.ownerId = ownerId;
		this.userId = userId;
		this.commentCode = commentCode;
		this.couponStatus = couponStatus;
	}


	public String getCouponCode() {
		return couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	public String getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getCommentCode() {
		return commentCode;
	}

	public void setCommentCode(int commentCode) {
		this.commentCode = commentCode;
	}

	public String getCouponStatus() {
		return couponStatus;
	}

	public void setCouponStatus(String couponStatus) {
		this.couponStatus = couponStatus;
	}


	@Override
	public String toString() {
		return "Coupon [couponCode=" + couponCode + ", ownerId=" + ownerId
				+ ", userId=" + userId + ", commentCode=" + commentCode
				+ ", couponStatus=" + couponStatus + "]";
	}

	
	

}
