package joojoo.entity;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Coupon implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** coupon_code. */
	private String couponCode;

	/** 새 테이블. */
	//private Owners owners;
	private String ownerId;

	/** 새 테이블. */
	//private Users users;
	private String userId;

	/** 새 테이블. */
	//private EventComment eventComment;
	private int commentCode;

	/** 새 테이블. */
	//private CouponStatus couponStatus;
	private int couponStatusCode;

	/**
	 * 생성자.
	 */
	public Coupon() {
	}

	public Coupon(String couponCode, String ownerId, String userId,
			int commentCode, int couponStatusCode) {
		super();
		this.couponCode = couponCode;
		this.ownerId = ownerId;
		this.userId = userId;
		this.commentCode = commentCode;
		this.couponStatusCode = couponStatusCode;
	}


	public String getCouponCode() {
		return couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	public String getOwnerId() {
		return ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getCommentCode() {
		return commentCode;
	}

	public void setCommentCode(int commentCode) {
		this.commentCode = commentCode;
	}

	public int getCouponStatusCode() {
		return couponStatusCode;
	}

	public void setCouponStatusCode(int couponStatusCode) {
		this.couponStatusCode = couponStatusCode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((couponCode == null) ? 0 : couponCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Coupon other = (Coupon) obj;
		if (couponCode == null) {
			if (other.couponCode != null) {
				return false;
			}
		} else if (!couponCode.equals(other.couponCode)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "Coupon [couponCode=" + couponCode + ", ownerId=" + ownerId
				+ ", userId=" + userId + ", commentCode=" + commentCode
				+ ", couponStatusCode=" + couponStatusCode + "]";
	}
	
	

}
