package joojoo.entity;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Coupon implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** coupon_code. */
	private String couponCode;

	/** 새 테이블. */
	private Owners owners;

	/** 새 테이블. */
	private Users users;

	/** 새 테이블. */
	private EventComment eventComment;

	/** 새 테이블. */
	private CouponStatus couponStatus;

	/**
	 * 생성자.
	 */
	public Coupon() {
	}

	/**
	 * coupon_code을 설정합니다..
	 * 
	 * @param couponCode
	 *            coupon_code
	 */
	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	/**
	 * coupon_code을 가져옵니다..
	 * 
	 * @return coupon_code
	 */
	public String getCouponCode() {
		return this.couponCode;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param owners
	 *            새 테이블
	 */
	public void setOwners(Owners owners) {
		this.owners = owners;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Owners getOwners() {
		return this.owners;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param users
	 *            새 테이블
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param eventComment
	 *            새 테이블
	 */
	public void setEventComment(EventComment eventComment) {
		this.eventComment = eventComment;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public EventComment getEventComment() {
		return this.eventComment;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param couponStatus
	 *            새 테이블
	 */
	public void setCouponStatus(CouponStatus couponStatus) {
		this.couponStatus = couponStatus;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public CouponStatus getCouponStatus() {
		return this.couponStatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((couponCode == null) ? 0 : couponCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Coupon other = (Coupon) obj;
		if (couponCode == null) {
			if (other.couponCode != null) {
				return false;
			}
		} else if (!couponCode.equals(other.couponCode)) {
			return false;
		}
		return true;
	}

}
