package joojoo.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EventComment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** comment_code. */
	private Integer commentCode;

	/** title. */
	private String title;

	/** content. */
	private String content;

	/** reg_date. */
	private Date regDate;

	/** start_date. */
	private Date startDate;

	/** end_date. */
	private Date endDate;
	
	private int storeCode;
	
	private int personsCode;
	private int serviceTypeCode;
	private String deleteRequest;
	/**
	 * 생성자.
	 */
	public EventComment() {}
	public EventComment(String title, String content, Date startDate,
			Date endDate, int storeCode, int personsCode, int serviceTypeCode) {
		super();
		this.title = title;
		this.content = content;
		this.startDate = startDate;
		this.endDate = endDate;
		this.storeCode = storeCode;
		this.personsCode = personsCode;
		this.serviceTypeCode = serviceTypeCode;
	}
	
	

	public Integer getCommentCode() {
		return commentCode;
	}
	public void setCommentCode(Integer commentCode) {
		this.commentCode = commentCode;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public Date getRegDate() {
		return regDate;
	}
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public int getStoreCode() {
		return storeCode;
	}
	public void setStoreCode(int storeCode) {
		this.storeCode = storeCode;
	}
	public int getPersonsCode() {
		return personsCode;
	}
	public void setPersonsCode(int personsCode) {
		this.personsCode = personsCode;
	}
	public int getServiceTypeCode() {
		return serviceTypeCode;
	}
	public void setServiceTypeCode(int serviceTypeCode) {
		this.serviceTypeCode = serviceTypeCode;
	}
	public String getDeleteRequest() {
		return deleteRequest;
	}
	public void setDeleteRequest(String deleteRequest) {
		this.deleteRequest = deleteRequest;
	}
	
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commentCode == null) ? 0 : commentCode.hashCode());
		return result;
	}



	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		EventComment other = (EventComment) obj;
		if (commentCode == null) {
			if (other.commentCode != null) {
				return false;
			}
		} else if (!commentCode.equals(other.commentCode)) {
			return false;
		}
		return true;
	}

}
