package joojoo.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RviewComment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** comment_code. */
	private Integer commentCode;

	private String userId;

	/** title. */
	private String title;

	/** content. */
	private String content;

	/** reg_date. */
	private Date regDate;

	/** star_point. */
	private Integer starPoint;

	/** 새 테이블. */
	private String storeName;

	/**
	 * 생성자.
	 */
	public RviewComment() {
	}

	public RviewComment(Integer commentCode, String userId, String title,
			String content, Date regDate, Integer starPoint, String storeName) {
		super();
		this.commentCode = commentCode;
		this.userId = userId;
		this.title = title;
		this.content = content;
		this.regDate = regDate;
		this.starPoint = starPoint;
		this.storeName = storeName;
	}
	
	

	public Integer getCommentCode() {
		return commentCode;
	}

	public void setCommentCode(Integer commentCode) {
		this.commentCode = commentCode;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getRegDate() {
		return regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public Integer getStarPoint() {
		return starPoint;
	}

	public void setStarPoint(Integer starPoint) {
		this.starPoint = starPoint;
	}

	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Override
	public String toString() {
		return "RviewComment [commentCode=" + commentCode + ", userId="
				+ userId + ", title=" + title + ", content=" + content
				+ ", regDate=" + regDate + ", starPoint=" + starPoint
				+ ", storeName=" + storeName + "]";
	}
	
	
	

}
