package joojoo.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Stores implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** store_code. */
	private Integer storeCode;

	/** store_name. */
	private String storeName;

	/** store_adress. */
	private String storeAdress;

	/** store_phone. */
	private Integer storePhone;

	/** owner_name. */
	private String ownerName;

	/** 새 테이블. */
	private Users users;

	/** 새 테이블. */
	private Region region;

	/** 새 테이블. */
	private StoreType storeType;

	/** star_point. */
	private Integer starPoint;

	/** 새 테이블 목록. */
	private Set<ReviewComment> reviewCommentSet;

	/** 새 테이블 목록. */
	private Set<EventComment> eventCommentSet;

	/**
	 * 생성자.
	 */
	public Stores() {
		this.eventCommentSet = new HashSet<EventComment>();
		this.reviewCommentSet = new HashSet<ReviewComment>();
	}

	/**
	 * store_code을 설정합니다..
	 * 
	 * @param storeCode
	 *            store_code
	 */
	public void setStoreCode(Integer storeCode) {
		this.storeCode = storeCode;
	}

	/**
	 * store_code을 가져옵니다..
	 * 
	 * @return store_code
	 */
	public Integer getStoreCode() {
		return this.storeCode;
	}

	/**
	 * store_name을 설정합니다..
	 * 
	 * @param storeName
	 *            store_name
	 */
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	/**
	 * store_name을 가져옵니다..
	 * 
	 * @return store_name
	 */
	public String getStoreName() {
		return this.storeName;
	}

	/**
	 * store_adress을 설정합니다..
	 * 
	 * @param storeAdress
	 *            store_adress
	 */
	public void setStoreAdress(String storeAdress) {
		this.storeAdress = storeAdress;
	}

	/**
	 * store_adress을 가져옵니다..
	 * 
	 * @return store_adress
	 */
	public String getStoreAdress() {
		return this.storeAdress;
	}

	/**
	 * store_phone을 설정합니다..
	 * 
	 * @param storePhone
	 *            store_phone
	 */
	public void setStorePhone(Integer storePhone) {
		this.storePhone = storePhone;
	}

	/**
	 * store_phone을 가져옵니다..
	 * 
	 * @return store_phone
	 */
	public Integer getStorePhone() {
		return this.storePhone;
	}

	/**
	 * owner_name을 설정합니다..
	 * 
	 * @param ownerName
	 *            owner_name
	 */
	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	/**
	 * owner_name을 가져옵니다..
	 * 
	 * @return owner_name
	 */
	public String getOwnerName() {
		return this.ownerName;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param users
	 *            새 테이블
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param region
	 *            새 테이블
	 */
	public void setRegion(Region region) {
		this.region = region;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Region getRegion() {
		return this.region;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param storeType
	 *            새 테이블
	 */
	public void setStoreType(StoreType storeType) {
		this.storeType = storeType;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public StoreType getStoreType() {
		return this.storeType;
	}

	/**
	 * star_point을 설정합니다..
	 * 
	 * @param starPoint
	 *            star_point
	 */
	public void setStarPoint(Integer starPoint) {
		this.starPoint = starPoint;
	}

	/**
	 * star_point을 가져옵니다..
	 * 
	 * @return star_point
	 */
	public Integer getStarPoint() {
		return this.starPoint;
	}

	/**
	 * 새 테이블 목록을 설정합니다..
	 * 
	 * @param reviewCommentSet
	 *            새 테이블 목록
	 */
	public void setReviewCommentSet(Set<ReviewComment> reviewCommentSet) {
		this.reviewCommentSet = reviewCommentSet;
	}

	/**
	 * 새 테이블를 추가합니다..
	 * 
	 * @param reviewComment
	 *            새 테이블
	 */
	public void addReviewComment(ReviewComment reviewComment) {
		this.reviewCommentSet.add(reviewComment);
	}

	/**
	 * 새 테이블 목록을 가져옵니다..
	 * 
	 * @return 새 테이블 목록
	 */
	public Set<ReviewComment> getReviewCommentSet() {
		return this.reviewCommentSet;
	}

	/**
	 * 새 테이블 목록을 설정합니다..
	 * 
	 * @param eventCommentSet
	 *            새 테이블 목록
	 */
	public void setEventCommentSet(Set<EventComment> eventCommentSet) {
		this.eventCommentSet = eventCommentSet;
	}

	/**
	 * 새 테이블를 추가합니다..
	 * 
	 * @param eventComment
	 *            새 테이블
	 */
	public void addEventComment(EventComment eventComment) {
		this.eventCommentSet.add(eventComment);
	}

	/**
	 * 새 테이블 목록을 가져옵니다..
	 * 
	 * @return 새 테이블 목록
	 */
	public Set<EventComment> getEventCommentSet() {
		return this.eventCommentSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((storeCode == null) ? 0 : storeCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Stores other = (Stores) obj;
		if (storeCode == null) {
			if (other.storeCode != null) {
				return false;
			}
		} else if (!storeCode.equals(other.storeCode)) {
			return false;
		}
		return true;
	}

}
