package joojoo.entity;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

public class Users {
	

	private String userId;

	private String userPassword;

	private String userName;

	private String userMail;

	private String userPhone;

	private Integer chance;
	
	
	
	

	public String getUserId() {
		return userId;
	}





	public void setUserId(String userId) {
		this.userId = userId;
	}





	public String getUserPassword() {
		return userPassword;
	}





	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}





	public String getUserName() {
		return userName;
	}





	public void setUserName(String userName) {
		this.userName = userName;
	}





	public String getUserMail() {
		return userMail;
	}





	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}





	public String getUserPhone() {
		return userPhone;
	}





	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}





	public Integer getChance() {
		return chance;
	}





	public void setChance(Integer chance) {
		this.chance = chance;
	}





	@Override
	public String toString() {
		return "Users [userId=" + userId + ", userPassword=" + userPassword
				+ ", userName=" + userName + ", userMail=" + userMail
				+ ", userPhone=" + userPhone + ", chance=" + chance + "]";
	}
	
	
	

}



