package joojoo.entity;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class WishList implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** wish_list_code. */
	private Integer wishListCode;

	/** 새 테이블. */
	private Users users;

	/** 새 테이블. */
	private EventComment eventComment;

	/**
	 * 생성자.
	 */
	public WishList() {
	}

	/**
	 * wish_list_code을 설정합니다..
	 * 
	 * @param wishListCode
	 *            wish_list_code
	 */
	public void setWishListCode(Integer wishListCode) {
		this.wishListCode = wishListCode;
	}

	/**
	 * wish_list_code을 가져옵니다..
	 * 
	 * @return wish_list_code
	 */
	public Integer getWishListCode() {
		return this.wishListCode;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param users
	 *            새 테이블
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param eventComment
	 *            새 테이블
	 */
	public void setEventComment(EventComment eventComment) {
		this.eventComment = eventComment;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public EventComment getEventComment() {
		return this.eventComment;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((wishListCode == null) ? 0 : wishListCode.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		WishList other = (WishList) obj;
		if (wishListCode == null) {
			if (other.wishListCode != null) {
				return false;
			}
		} else if (!wishListCode.equals(other.wishListCode)) {
			return false;
		}
		return true;
	}

}
